CREATE DATABASE TESTE;
USE TESTE;

CREATE TABLE PESSOAS (
NOME VARCHAR (50),
SALARIO INT,
DATA_NASCIMENTO DATE
);

-- CRUD 
-- CREATE = INSERT 
-- READ = SELECT (WHERE)
-- UPDATE = UPDATE
-- DELETE = DELETE

-- ALTERAR TABELA PRA ADICIONAR UMA COLUNA NA TABELA SEM MEXER NA ESTRUTURA DO CÓDIGO
ALTER TABLE PESSOAS ADD COLUMN PROFISSAO VARCHAR(40); 

-- O * É PARA SELECIONAR TODOS AS COLUNAS DE UMA DETERMINADA TABELA CHAMADA PELO FROM
SELECT * FROM PESSOAS;

-- INSERIR DADOS NAS COLUNAS DENTRO DAS TABELAS
INSERT INTO PESSOAS (NOME, SALARIO, DATA_NASCIMENTO, PROFISSAO)
VALUES ('MARCOS',4000,'1971-04-16','LOGÍSTICA');

-- SELECIONAR TODOS DA TABELA PESSOAS ONDE SALARIO FOR > QUE 3000
SELECT * FROM PESSOAS WHERE SALARIO >3000;

-- AQUI SELECIONEI APENAS COM MEU NOME
SELECT * FROM PESSOAS WHERE NOME = 'LEONARDO';

-- USA ISSO PRA DAR UPDATES EM QUALQUER COLUNA SEM PRECISAR SETAR EM FK OU PK
SET SQL_SAFE_UPDATES =0;

-- ATUALIZANDO NA TABELA PESSOAS COLOCANDO UM SALARIO DE 0 NO NOME LEONARDO :( 
UPDATE PESSOAS SET SALARIO = 0 WHERE NOME = 'LEONARDO';

-- AQUI REMOVE QUEM TIVER A PROFISSAO DE PROGRAMADOR NO SISTEMA
DELETE FROM PESSOAS  WHERE  PROFISSAO = 'PROGRAMADOR';

DROP TABLE PESSOAS;

-- ---------------------------------------------CONSTRAINTS--------------------------------------------- --
CREATE TABLE PESSOAS (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL, -- INCREMENTA UM ID A MAIS DOQ O ULTIMO
NOME VARCHAR (30),
SALARIO INT,
DATA_NASCIMENTO DATE
);

ALTER TABLE PESSOAS ADD COLUMN PROFISSAO VARCHAR(100);

INSERT INTO PESSOAS (NOME, SALARIO, DATA_NASCIMENTO, PROFISSAO)
VALUES ('BEATRIZ', 20000, '2004-11-21', 'BIO-QUIMICA');

SELECT * FROM PESSOAS;

-- COLOQUEI O NOME EM MAIÚSCULO
UPDATE PESSOAS SET NOME = 'LEONARDO' WHERE NOME ='lEONARDO';


